name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: yarn
      - run: yarn lint
      - run: yarn test
