name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: docker-compose -f docker-compose.build.yml up --build --exit-code-from app
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: web-ext-artifacts/
